### ISSUE TITLE
Revert #136 once the gcc9 performance issues are resolved

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd-centos-ci#137]
See:
* #136
* https://github.com/systemd/systemd/pull/12856
* https://bugzilla.redhat.com/show_bug.cgi?id=1722949

**Comment by mrc0mmand** [comment]
@evverx I filed the GCC issue to upstream bug tracker with some statistics (possibly explaining the performance issues), if you're interested: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91101

**Comment by evverx** [comment]
@mrc0mmand thank you. In the meantime, I think it should be possible to keep rolling forward by reverting that commit where the repositories were pinned and either turning off the stage where the code is built with gcc+ASan or by stopping passing `detect_stack_use_after_return=1` there. It should be safe because it's already covered by the "clang" stage.

**Comment by mrc0mmand** [comment]
@evverx that would indeed make sense; and given the response from the gcc guys, it looks like there might be some additional tweaks necessary https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91101#c15

**Comment by mrc0mmand** [comment]
Fixed in #146
