### ISSUE TITLE
Intermittent LSan fail in `test-execute`

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd-centos-ci#156]
Under very rare circumstances (~5 times in the last month) the LSan failed during `test-execute` in the sanitizers job:

```
hild 16030 (sh) died (code=exited, status=0/n/a)
exec-systemcallfilter-system-user-nobody.service: Failed to read oom_kill field of memory.events cgroup attribute: No such file or directory
exec-systemcallfilter-system-user-nobody.service: Child 16030 belongs to exec-systemcallfilter-system-user-nobody.service.
exec-systemcallfilter-system-user-nobody.service: Main process exited, code=exited, status=0/n/a
exec-systemcallfilter-system-user-nobody.service: Succeeded.
exec-systemcallfilter-system-user-nobody.service: Changed start -> dead
Tracer caught signal 11: addr=0x0 pc=0x7fad92aafba8 sp=0x7fad8b5ced00
==11065==LeakSanitizer has encountered a fatal error.
==11065==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==11065==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
```

Full log: https://ci.centos.org/job/systemd-pr-build-vagrant-sanitizers/1493/artifact//systemd-centos-ci/artifacts_all/artifacts_v3PKm7/vagrant-logs.Rol/vagrant-arch-sanitizers-clang-testsuite.rCB/ninja-test_sanitizers_FAIL.log

**Comment by mrc0mmand** [comment]
cc @evverx, if you, by any chance, have any idea what may be the culprit :-)

**Comment by mrc0mmand** [comment]
Also, it looks like it happens always at the same place. This is an excerpt from a different report:

```
exec-systemcallfilter-system-user-nobody.service: Changed start -> dead
Tracer caught signal 11: addr=0x0 pc=0x7fbcc2fa9f60 sp=0x7fbcbbacecd0
==6127==LeakSanitizer has encountered a fatal error.
```

Maybe the `SystemCallFilter=` messes up with LSan in some racy way?

**Comment by evverx** [comment]
Looks like LSan segfaults trying to access memory after `exec-systemcallfilter-system-user-nobody.service` has finished. I'm not sure what exactly is going on but I was once told that generally sanitizers aren't compatible with seccomp filters (or any other way of restricting processes) and the issue was open for more than a year if I recall correctly :-) The bug was fixed on the clang side eventually but they usually recommend turning off seccomp filters, which, in this particular case, isn't possible as far as I can tell. We can just skip the subtest under ASan though.

**Comment by mrc0mmand** [comment]
Excellent, thanks a lot for the explanation! Will prepare a patch for the systemd repository.
