### ISSUE TITLE
ci: CentOS CI (Arch Linux + sanitizers) does not show enough coredump info

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd-centos-ci#465]
https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/10231/artifact//systemd-centos-ci/artifacts_all/artifacts_qaprlflj/vagrant-logs.WCa/vagrant-arch-sanitizers-clang-testsuite.stJ/coredumpctl_collect_FAIL.log

Note: CentOS CI (Arch Linux) shows well.
https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux/10295/artifact//systemd-centos-ci/artifacts_rxm7x5az/vagrant-logs.twN/vagrant-arch-testsuite.IkL/coredumpctl_collect_FAIL.log

**Comment by mrc0mmand** [comment]
This is actually expected, because in the sanitizers run ASan maps the whole virtual address space (16TB). Which means when dumping a core of a ASan-aware binary, we trip over the coredump limit:

```
Feb 25 04:35:02 arch.localdomain systemd-coredump[76056]: Resource limits disable core dumping for process 76050 (systemd-network).
Feb 25 04:35:02 arch.localdomain systemd-coredump[76056]: Process 76050 (systemd-network) of user 980 dumped core.
```

I'm not really sure if there's anything I could do in this case, since that's how ASan works[0].

[0] https://clang.llvm.org/docs/AddressSanitizer.html#limitations
> On 64-bit platforms AddressSanitizer maps (but not reserves) 16+ Terabytes of virtual address space. This means that tools like ulimit may not work as usually expected.

**Comment by yuwata** [comment]
Thank you for the clarification. It is OK if this is the expected behavior. Closing.
