### ISSUE TITLE
TEST-01-BASIC is started after systemd-networkd-tests.py finished on CentOS 8

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd-centos-ci#510]
From https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/9151/console
```
15:58:33 [PARALLEL TASK] TEST-01-BASIC (/bin/time -v -- make -C test/TEST-01-BASIC setup run && touch /var/tmp/systemd-test-TEST-01-BASIC/pass)
16:31:45 [RESULT] systemd-networkd-tests.py - PASS (log file: /root/testsuite-logs-upstream.DfN/systemd-networkd-tests.py_PASS.log)
16:31:45 
16:31:45 [PARALLEL TASK] TEST-02-UNITTESTS (/bin/time -v -- make -C test/TEST-02-UNITTESTS setup run && touch /var/tmp/systemd-test-TEST-02-UNITTESTS/pass)
16:32:08 [RESULT] TEST-01-BASIC - PASS (log file: /root/testsuite-logs-upstream.DfN/TEST-01-BASIC_PASS.log)
```
So, it seems to take ~33 min. But that's not correct. From the log https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/9151/artifact/systemd-centos-ci/artifacts_95xgzhe7/testsuite-logs-upstream.DfN/TEST-01-BASIC_PASS.log,
```
[TASK START] Mon Jul 11 16:31:45 CEST 2022         <------ This is the exactly same time when networkd test finished.
make: Entering directory '/root/systemd/test/TEST-01-BASIC'
...
TEST-01-BASIC RUN: Basic systemd setup [OK]
make: Leaving directory '/root/systemd/test/TEST-01-BASIC'
	Command being timed: "make -C test/TEST-01-BASIC setup run"
	User time (seconds): 11.03
	System time (seconds): 3.45
	Percent of CPU this job got: 62%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:23.24
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 382572
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 97
	Minor (reclaiming a frame) page faults: 154597
	Voluntary context switches: 61605
	Involuntary context switches: 2449
	Swaps: 0
	File system inputs: 477306
	File system outputs: 517208
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
[TASK END] Mon Jul 11 16:32:08 CEST 2022
```
So, why TEST-01-BASIC and other tests are started after the networkd test?

On Arch CI, TEST-XX seem to run in parallel with the networkd test.

**Comment by mrc0mmand** [comment]
This actually depends on the machine we get from the pool. The CentOS CI pool consists of five different chassis (https://wiki.centos.org/QaWiki/PubHardware). I can parallelize stuff on four of them, since the `dusty` chassis is less powerful (and parallelization causes frequent issues). So, up until a ~month ago, you'd have 1 in 5 chance to hit the `dusty` chassis, where the tasks are run in a serialized manner.

Unfortunately, due to HW issues, ~two months ago two chassis died a couple of days apart - `hufty` and `pufty` - so the chance of hitting a `dusty` node rose to 1 in 3. Also, the `gusty` chassis has been having some issues recently as well, which bumps the chance even more, as some of the nodes are ending up in a HW failure state.

Since the machines are out of warranty, there's not much the CentOS Infra guys can do. However, there's an ongoing migration of the whole machine pool to AWS (the first part is scheduled to August), which should, hopefully, help with the performance.

**Comment by yuwata** [comment]
Indeed. I found the following in the same console log.
```
15:53:59 [source] Running on a *.dusty machine, overriding the # of CPUs to 4 and queue size to 1
15:53:59 [TASK-CONTROL] OPTIMAL_QEMU_SMP = 4
15:53:59 [TASK-CONTROL] MAX_QUEUE_SIZE = 1
```
