### ISSUE TITLE
restarting TEST-64 causes whole test timeout

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd-centos-ci#635]
and journal files for failed tests will be lost.

As TEST-64 takes much longer time, so maybe better to not restart it when it fails.

**Comment by mrc0mmand** [comment]
This shouldn't be an issue now, since d2d6169 the C8S job runs only nspawn tests in PR runs, as thanks to unaccelerated QEMU pegging the vCPUs at 100% almost all the time we'd get rate limited almost every day, causing timeouts. To account for the lost coverage the [daily cron job](https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-cron-build/) does the full run on C8S (and so far it stays within the limits and not triggering any rate limiting). Also, the Arch Linux jobs still run both nspawn and QEMU tests, as they run on bare metal machines (at least for now).

It's an unfortunate situation, but there's not much else I can do here.

**Comment by yuwata** [comment]
I see. Thank you for the consideration and explanation.
